### ISSUE TITLE
Need login logic to be completed

### ISSUE THREAD

**Issue by cwgu** [Intro-to-SE-Lab-Fall-20/Group-13#1]

**Comment by Jhowardmsstate** [comment]
Lets identify core requirements and define the process workflow. For example, Open website, enter username, enter password, click "Login" button. Define the logic behind what occurs in our software once a user clicks "Login"

What backend systems are involved and what are the traffic flows for authentication? etc.

**Comment by Jhowardmsstate** [comment]
Added proper labels to this issue and created new label "Requirement Code Work" to identify this as a pre-step to coding.

**Comment by cwgu** [comment]
Added new code to address issue. Included basic login logic and implemented route.
