### ISSUE TITLE
FINAL Review of SRS document and User Stories for Sprint 1 --Due Date: Sep 3 2020.

### ISSUE THREAD

**Issue by Jhowardmsstate** [Intro-to-SE-Lab-Fall-20/Group-13#11]
Team - please review the SRS and user stories for Sprint 1 turn in.
Leave comments here if changes have been made.
Files will be marked completed and turned in Sep 2 at 3:00PM.

**Comment by cwgu** [comment]
@Jhowardmsstate taking a look at it now.

**Comment by Jhowardmsstate** [comment]
Met with Rayhan Sep 1 Tuesday 2:30pm. He reviewed our SRS and all was correct. No changes were recommended.

**Comment by Jhowardmsstate** [comment]
SRS document is a living document. This review thread is closing as we continue development. As needed a new topic will be created.
