### ISSUE TITLE
Build new route for with form for search

### ISSUE THREAD

**Issue by cwgu** [Intro-to-SE-Lab-Fall-20/Group-13#12]
A new route needs to be built that offers a form for search and a return value that implements the query.

View email-search route for more information

**Comment by WilliamGiddens** [comment]
Currently looking at this issue. Discussing with Chad.

**Comment by cwgu** [comment]
The route for search should include access Nilas api for search and pass search query

**Comment by cwgu** [comment]
Just checking in to see if you had any issues on the issue.

**Comment by cwgu** [comment]
Checking in on status. Do you all have questions?

**Comment by WilliamGiddens** [comment]
Finished search. Going to push tomorrow.

**Comment by cwgu** [comment]
Were there any changes pushed to the email search template? The form does not seem to be implemented/

**Comment by cwgu** [comment]
Having issues with form for search. Need to address Query. Working on code. Search working, just query.

**Comment by cwgu** [comment]
Closing issue, will open new issue to address query.
