### ISSUE TITLE
Build new route for create new email

### ISSUE THREAD

**Issue by cwgu** [Intro-to-SE-Lab-Fall-20/Group-13#13]
A new route for composing new email is needed. Should be added to app.py. This may also require a new compose template.

**Comment by cwgu** [comment]
Checking on to see if you have any questions on this item.

**Comment by Jhowardmsstate** [comment]
Chad as our lead developer are we using the following? I have the code mostly complete in a fork that I have not pushed yet.
app.config['MAIL_PORT'] = 587
app.config['MAIL_USE_TLS'] = True

also email body is html not text correct?

**Comment by cwgu** [comment]
Joe, I think everything will be API driven for the mail server. We shouldn't need ports. I have fished the other issue and can code this if you want. Let me know by assigning to me as well.

**Comment by Jhowardmsstate** [comment]
Port requirements are validated as not needed beyond 443 SSL. Issue 19 raised this question from the client and has been closed.
