### ISSUE TITLE
Travis CI setup

### ISSUE THREAD

**Issue by cwgu** [Intro-to-SE-Lab-Fall-20/Group-13#14]
Look at using Jenkins for Bonus and possibly later work.

**Comment by Jhowardmsstate** [comment]
I have configured and added Travis CI to my separate repository to test prior to potential use in our environment. https://travis-ci.com/  
Note, this has not been introduced to our environment at this time. This tool is in test for use in our project.

**Comment by cwgu** [comment]
Added Joe to issues

**Comment by cwgu** [comment]
Changed name to match new Travis CI choice.,

**Comment by Jhowardmsstate** [comment]
![Travis-CI](https://user-images.githubusercontent.com/70033151/94216314-aab06500-fea4-11ea-83ae-cda719929f76.JPG)

**Comment by Jhowardmsstate** [comment]
Completed Project Integration with Travis-CI to facilitate continuous integration for test infrastructure. No tests have been created but the platform has been integrated and configured for use.
![Travis-CI](https://user-images.githubusercontent.com/70033151/94216727-bbada600-fea5-11ea-93fa-e1c8063f0a8d.JPG)

**Comment by Jhowardmsstate** [comment]
The team has completed the integration of Travis CI to be used in our project in an ongoing matter. The platform is stable and the team is reviewing and deciding on proper test case to be used with this enhancement.
