### ISSUE TITLE
Need to get pictures of teammembers for Profile

### ISSUE THREAD

**Issue by cwgu** [Intro-to-SE-Lab-Fall-20/Group-13#2]
Will need a picture of each team member for the team section of the README.md file

**Comment by Jhowardmsstate** [comment]
![JoeHoward](https://user-images.githubusercontent.com/70033151/91564547-631ad580-e906-11ea-903e-0d757bf92d72.jpg)

**Comment by Jhowardmsstate** [comment]
Team Member: Joe Howard Lab Group 13

**Comment by Jhowardmsstate** [comment]
This issue has been confirmed completed and closed 8/28/2020.
