### ISSUE TITLE
Customer Meeting 9/22 - Priority 3 - Question Shared Credentials

### ISSUE THREAD

**Issue by Jhowardmsstate** [Intro-to-SE-Lab-Fall-20/Group-13#20]
William & Team:
The client has asked if they can use single shared credentials for group mailboxes.

Please advise on client response.
Joe

**Comment by WilliamGiddens** [comment]
Yes, you can share credentials in this system. It does not enforce or govern your corporate security policy. Traditional corporate security polices frown on this but the email client is not enforcing security requirements in this regard.

**Comment by Jhowardmsstate** [comment]
Thank you for the clarification on this issue. I will take this information forward to the next client meeting scheduled for 10/6/2020.
