### ISSUE TITLE
Customer Meeting 9/22 - Priority 2 - Question Can the user have multiple accounts?

### ISSUE THREAD

**Issue by Jhowardmsstate** [Intro-to-SE-Lab-Fall-20/Group-13#21]
Trey & Team:
The client has asked if their users can have multiple accounts. 

Please advise on client response.
Joe

**Comment by trekkertrey** [comment]
Yes, a user can have multiple accounts; however, each account requires an individual email address. The email client system will not merge or combine views across the different accounts. Each account is stand-alone.

**Comment by Jhowardmsstate** [comment]
Thank you for the clarification on this issue. I will take this information forward to the next client meeting scheduled for 10/6/2020.
