### ISSUE TITLE
Validate class diagram is consistent with the code for SPrint 3

### ISSUE THREAD

**Issue by Jhowardmsstate** [Intro-to-SE-Lab-Fall-20/Group-13#26]
Architecture  Validate class diagram is consistent with the code

**Comment by WilliamGiddens** [comment]
![classdiagramsprint3](https://user-images.githubusercontent.com/70033116/96822074-d7499500-13ee-11eb-9e55-02b04f1ec87a.jpg)

**Comment by WilliamGiddens** [comment]
This diagram is consistent with the code

**Comment by Jhowardmsstate** [comment]
Validation complete. This task is closed.
