### ISSUE TITLE
Review Commit logs for quality  Sprint 3

### ISSUE THREAD

**Issue by Jhowardmsstate** [Intro-to-SE-Lab-Fall-20/Group-13#28]
1. Commit   logs descriptive,      
2. Commits referenced with issues,     
3. Discussion resolved for Sprint 3      
4. Review in github
--

**Comment by Jhowardmsstate** [comment]
Review has been completed on 10-21 and all commit logs are verified as descriptive and code review has been completed for proper comments.

**Comment by WilliamGiddens** [comment]
Agreed. Commit logs are well put together and describe our code well.

**Comment by cwgu** [comment]
After our meeting with Rayhan, I tried to eloborate issue number for most commits.
