### ISSUE TITLE
Vendor Props

### ISSUE THREAD

**Issue by Jhowardmsstate** [Intro-to-SE-Lab-Fall-20/Group-13#38]
Credit from the vendors to our lead developer Chad W.

From: Nylas Swag <swag+noreply@nylas.com>
To: <chadwhitney@zohomail.com>
Date: Fri, 25 Sep 2020 16:44:26 -0700
Subject: Re: With Love, from Nylas
============ Forwarded message ============

Hello Friend,

Thank you for taking the time to test the Nylas Email API! As a token of our appreciation, we'd like to offer to mail you some Nylas swag! If you live in this US, fill out the following form and we'll send you some free stickers.
https://nylas.typeform.com/to/u6sm53

The Nylas Communications Platform is the quickest, safest, and easiest way to connect your application to every inbox, calendar, and contacts book in the world. Take a look at our getting started guide to learn more: https://docs.nylas.com/docs/getting-started
@cwgu

**Comment by Jhowardmsstate** [comment]
![Nylas](https://user-images.githubusercontent.com/70033151/99088038-1784d900-2591-11eb-94b3-f571cbbf5d8f.jpg)

**Comment by Jhowardmsstate** [comment]
Well done Chad & thank you.

**Comment by cwgu** [comment]
Hah, got mine too! Nylas was great software to work with. Great people solving real problem.

![nylas](https://user-images.githubusercontent.com/47794768/99089601-25d3f480-2593-11eb-944c-ebd4b2df84c7.jpg)
