### ISSUE TITLE
Add the Description of the Project to README.md

### ISSUE THREAD

**Issue by cwgu** [Intro-to-SE-Lab-Fall-20/Group-13#4]
Add a H2 tag to the README.md file 

Detail the description of the project

**Comment by Jhowardmsstate** [comment]
Working on issue #4. Added Project description heading to README.md

This project aims to provide an applicable solution for handling the storage and retrieval of emails. The use of advanced object-oriented techniques will provide a foundation for further developers to create and deploy advanced versions of the tool. The foundation provided by the development of this project will be a step toward creating additional enhancements and features in subsequent releases; with each focusing on one specialized part of the email tool. The scope of the project is to meet the features requested from the user community in the initial project request and allow for two small incremental changes to the software. 

The software product being created will be a web based email platform that will allow users to login and view their emails. Emails can be created and sent with or without attachments. A user will also be able to search email by subject and then forward an email to another email address. 

8/28/2020 Commit Changes to README.md

**Comment by Jhowardmsstate** [comment]
Added additional line to specify that this is a web application. This resolves Issue #4.
