### ISSUE TITLE
Lab Meeting with Rayhan Amin 8/28 Issue: Modification to User Stories per Guidance

### ISSUE THREAD

**Issue by Jhowardmsstate** [Intro-to-SE-Lab-Fall-20/Group-13#8]
Post Lab Meeting
Meeting Attendees: Rayhan Amin, Chad Whitney, Joe Howard 
In this meeting we identified some required modifications to our user stories.
Our lab team must modify the user stories to articulate each requirement action as a stand-alone story at a higher level than what we originally had.
This change will allow for further additions as the project progresses as sub-stories.
Action: 
Re-work each action to be a stand-alone action. For example, Compose email & Forward email

**Comment by cwgu** [comment]
I have altered the user stories to better match the requirements discussed in the meeting with Mr. Rayhan. These stories should appear in the WIKI under USER STORIES.
